apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: httproutes
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 3m
  prune: true
  path: ./kubernetes/apps/network/httproutes
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: envoy-gateway-config
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
