# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:xB+x6GVjnPCRjGTbUEuHMg==,iv:jrKXKAY3gpXoHB7X4zca3/69yHqsCs1hv/H+thpT6lw=,tag:TJKgAwfAzY4hnmPeCWTI+Q==,type:comment]
    SECRET_DOMAIN_0: ENC[AES256_GCM,data:v7RrUnKrynO4Rq266w==,iv:4mbauUuDXKB6OkneXDCau1moOj7Ir8AVVPqJ5MUNU+g=,tag:hp+ECXfKtM1kpc4EK8dWNg==,type:str]
    SECRET_DOMAIN_1: ENC[AES256_GCM,data:o89Rmd3gFKwyzKy8wJzMxuMWIXCr2Q==,iv:mG0Ri8ut3ZMLqajlAlM7lcXQ28h0I7d4k1VzvwjpDhs=,tag:F9mFrTjGf2kd97ivMclvZg==,type:str]
    #ENC[AES256_GCM,data:k+r86ON0n5E95UjmR17w20lT/lMm2yjp1cbsjQ6ipb7ZzEjOpBmcwExt,iv:6M77fcWRaZ60LsvdnmIayGjAN78IfiTe/VRXaujdxmE=,tag:j/d7+Z0riwbJA6Jjz0Cn7A==,type:comment]
    CLOUDFLARE_CERT_MANAGER_TOKEN: ENC[AES256_GCM,data:5nj/50ek1ydUoqkmXfX4xcuYdh9EH7+GoC+beZkXRp+3jPRk9h/b3g==,iv:I6LtSGXiuXSPBapZphc9jvrqfg9M9w0URktOI6OjvZo=,tag:TVdO/6anZaieaRZclNQVHQ==,type:str]
    #ENC[AES256_GCM,data:ZAYB8swwWopKPyq78KQxnPRxUTW8k9zltFc=,iv:LfKZwlNVenRFnUXANXvo0xeIX2CvZPk3bvwLxkugsZ0=,tag:/9QXxoqw8iOHywZbwY8l9A==,type:comment]
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:VWhup+IGHnUIKwXg7rtW3xnpeLkRfpDbzrU9Rr0SCRA=,iv:/T/C7Hu1E15nQmIfhNvAsNr2PDHNsbI1/A2F6tKQ2kY=,tag:VRbVMN0SyedXZpeLmNgxRQ==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RHV4YwwPq5zzevlvGIDunp6E6ZncqG+PVBJfauk=,iv:y1DQNCyPaB0OsjDZlEBWY8aBt79O7Ei8r9gAPSugNUM=,tag:09no/vBlbP3NxZeLcolXWg==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT3RNV1pEWTJ2MkpLQlkr
            UnUvSUc5a21BZXEyOVJxeS94aUk0YXF0TEJvCjZnM1VvMWdvdSthdWxJOG1ibzdG
            MzdDQVIxZmVYSWUrSWdScVljSURUeXMKLS0tIE9ZbVpEakx3SzR3WEZQTVdqV2dv
            dkgwNTR1aHFReW5tZnBkYzFjZ0JSdWsKNSRWg/1G3DproZWQKSO6agDVWS2sEKL6
            F1knLCufQ9PcOqE8cjRETCxe3AiDLZMqVFDhuf0RPaKgi9RxjFfeMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T11:53:06Z"
    mac: ENC[AES256_GCM,data:p6Le5IDNBKzOTWQoXzmGQhuSPYpZ8eCVlfDgEnqKYKquB7YXm3RNGjDdQP6t+kLooOaAB3PsZG+T245Pso/P9d+uZxu7I8LtQCJmJAklLXJkFD1PAJ/YEbbKMNn6MESrA4C4geECVq8Pqx0jaZVymE+wlxxQG7ytzKFSVmGuZEo=,iv:yuSXurBoMPqpdywR0Al7q8ewU3rf2eBaGj97c3wWJMQ=,tag:gsYlgaX2fj7oMvRR2rmivw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
