# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    TZ: ENC[AES256_GCM,data:cuhEFqej4lAY6ov2Tu6P4w==,iv:QWfENT45LvHtyw1p+sLJL65UoczKjclkcX4VT3D3cdE=,tag:FEjM+q54oxLu6bVU4v9QFg==,type:str]
    SECRET_DOMAIN_0: ENC[AES256_GCM,data:ucTTuG9oH8kQKnDmfQ==,iv:SfQNThEZhtJGIGDUMkDOVi4V8wpYekfyPYAKwwSaEwc=,tag:fbUxvJEWKI3K+GwYHfX3nA==,type:str]
    SECRET_DOMAIN_1: ENC[AES256_GCM,data:Nkjk7wrlCh2ZHhXuq0Q=,iv:6rYwh2w7Bow6JWA7qyJSmqHd0TpgGPdcOeHs/KwRPU0=,tag:yOltT9lHOLGqbA4TEhaPVQ==,type:str]
    CLOUDFLARE_CERT_MANAGER_TOKEN: ENC[AES256_GCM,data:NqutFOdABTOKK5TJFQAjs15HR1hO6Vy0rNf1t5vSjgq05bUsqIPkwQ==,iv:qYXu9EweU3l4wdp+ZDR7/9FAEtLJVDC/TtjXSXDwue8=,tag:BVfAnAKK3x91xl7L20/h5A==,type:str]
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:kNVLs9H0uzJN9fVXEDssFvrTTr4e778Ng4beSv7/tzlElNLcz/5ucAYJvNQCT/9ZDECmBdr2XSCPsNmIJNqqK3LcyLrLT8zxLc86gyfNWZg6eU24w2QTrfYXaEJRHJPl2rdDUFjbepl9fpSxpjgXdwfmTogcqTzGKEvPid+k0UizBF3/lyxmsUBvFUJTRGtVcSunbCFYdZIJcpu/duSh9I/a8Qi8xYOeTLtNpoN2LV5YGabi8GHFMA==,iv:mW27/74fT2lbqUR5tQfumSiiZNta+Vgjy/8kG4Xxzj0=,tag:7BJB4y1BlXSi0gX9YkAIOQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:mMNRnn3mi01N2lfKg5t2nKIvYw==,iv:kdY03T0DCVs+oLf8vAPNyixYMnK/sTel8K8HbZeLAD4=,tag:Ak9xZyv5hqZ8GWtshw37aQ==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MNH011iOiSmO1x/R+VGBXUvO8i0GtPAZaHjeMaHUnON5wH+Y,iv:Ls9ENydAsEq/vvvMLT2C6hxVZoNpOghhwTSz8MZu3lU=,tag:nFw1r4vMOfkXbOSSFH0nIg==,type:str]
    AIOSTREAM_SECRET_KEY: ENC[AES256_GCM,data:kY9cec6G26guBGSg6IHUATTGM3kUUWBHk+ES/lgzcjC5LV/3uIXsMdQQ1PLlvF4ZNHVZeR+KiaNXqcm7bII1nw==,iv:8pesItJyQsz0ErJetYiSOIaFDYSaC+k0kEZDfG4kZCs=,tag:+z8ySVeFeaPxuHhHQPWyKQ==,type:str]
    AIOSTREAM_ADDON_PASSWORD: ENC[AES256_GCM,data:8oZl5rYV6xFMhx/JxpyAJNr1iWCmQV8I,iv:ZNOIpPn8Ht4F71VZe1DcoIWBLKt9ESvxLslLxxZYtL8=,tag:d4oVWlKDPZJdrZjYrrRJsQ==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWDB5bldncTluNWk1Uk0x
            SnJoWWJNN2NVVU9VanVRWHA4RHY3REl3UDI4Cm5oQzBtZVFoNHFxZTIvZTQ1ckxP
            ZVVsWG9ISE81QVJyZ3VGUU03b1FOclEKLS0tIDNvcFQ3UkpGV01maDJQMVJkdnhG
            M1c3OENVb1BwT1h0bm42OEJPcm5zbnMK4bGiT/zC9BuxiQW0p2MLyZtyOPhWanTL
            xQGId3ToadUQNjSexkuQ/6RvT8VicArpgHp94s5XJ6lSDOBHfC/eDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T19:10:39Z"
    mac: ENC[AES256_GCM,data:ctwDcH4EziTTi288qBq1DzE1TSa6E6D5gE0QRZOeEW8eRyeH3VAIL2OWJGaL+s+3RDFgyB9g2PV1oFs8v4GgfA4POywNacrKAo6IndFi0jqXHbgrbkNOmj1RL28sHxDMzquX8za+Vici6bTykOlM8pdfBr8Fz7qop3/PJEb9VGc=,iv:NAGzl3WgnrRiS7HpAMsq4njDBzx/sQK2wekWio6LbAg=,tag:eFFMMPY/x8Fnt7RoxHS0Eg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
