# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:xB+x6GVjnPCRjGTbUEuHMg==,iv:jrKXKAY3gpXoHB7X4zca3/69yHqsCs1hv/H+thpT6lw=,tag:TJKgAwfAzY4hnmPeCWTI+Q==,type:comment]
    SECRET_DOMAIN_0: ENC[AES256_GCM,data:v7RrUnKrynO4Rq266w==,iv:4mbauUuDXKB6OkneXDCau1moOj7Ir8AVVPqJ5MUNU+g=,tag:hp+ECXfKtM1kpc4EK8dWNg==,type:str]
    SECRET_DOMAIN_1: ENC[AES256_GCM,data:o89Rmd3gFKwyzKy8wJzMxuMWIXCr2Q==,iv:mG0Ri8ut3ZMLqajlAlM7lcXQ28h0I7d4k1VzvwjpDhs=,tag:F9mFrTjGf2kd97ivMclvZg==,type:str]
    #ENC[AES256_GCM,data:k+r86ON0n5E95UjmR17w20lT/lMm2yjp1cbsjQ6ipb7ZzEjOpBmcwExt,iv:6M77fcWRaZ60LsvdnmIayGjAN78IfiTe/VRXaujdxmE=,tag:j/d7+Z0riwbJA6Jjz0Cn7A==,type:comment]
    CLOUDFLARE_CERT_MANAGER_TOKEN: ENC[AES256_GCM,data:5nj/50ek1ydUoqkmXfX4xcuYdh9EH7+GoC+beZkXRp+3jPRk9h/b3g==,iv:I6LtSGXiuXSPBapZphc9jvrqfg9M9w0URktOI6OjvZo=,tag:TVdO/6anZaieaRZclNQVHQ==,type:str]
    #ENC[AES256_GCM,data:ZAYB8swwWopKPyq78KQxnPRxUTW8k9zltFc=,iv:LfKZwlNVenRFnUXANXvo0xeIX2CvZPk3bvwLxkugsZ0=,tag:/9QXxoqw8iOHywZbwY8l9A==,type:comment]
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:F0i1XjhZKuwhNWYzlUWCUh4PpWsavtnazw+8YEoEx4OpQiSGFG833z/NIWvkGoyklA6+qzuVSjMd27gXtivU2i1qv0N8Tgbm1IpNBh1YO6DfyzNP8I80HaQIryNUSDT/GHdzT2/LEpE+XiWLP3jQmDqYb2gI//5IkvQSWbWhOXBD4Zw8LNH60b+VzmH3PPLzHsdnXn39E08sNSyK1U/NqlE2MQWT+BeJdpZEFQJ9D1qmwU6mOq/bHQ==,iv:+tNjMKy2Io8AUiZpiSeNygrXcLRH0iC7vUtCZQY1bc8=,tag:XnKkGeae87LKomyCK+1JeQ==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Nw==,iv:5AyEFSmwes80vva/hR++FiG6PA0rFEfygapZbXnqRsA=,tag:54WDER5kqo8/Bpu5IuUXfA==,type:int]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT3RNV1pEWTJ2MkpLQlkr
            UnUvSUc5a21BZXEyOVJxeS94aUk0YXF0TEJvCjZnM1VvMWdvdSthdWxJOG1ibzdG
            MzdDQVIxZmVYSWUrSWdScVljSURUeXMKLS0tIE9ZbVpEakx3SzR3WEZQTVdqV2dv
            dkgwNTR1aHFReW5tZnBkYzFjZ0JSdWsKNSRWg/1G3DproZWQKSO6agDVWS2sEKL6
            F1knLCufQ9PcOqE8cjRETCxe3AiDLZMqVFDhuf0RPaKgi9RxjFfeMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T12:39:15Z"
    mac: ENC[AES256_GCM,data:ytx9woZv793ReH24Ac9NbWkxWlQcN3ZFIuvKtYKQmFIAadeehLSjHMcRncidyY4F316GGkRm9gXs2ZpFbY9gcbYnk20pDGAONT6Gkf1fvy+jQxs/B9ENCxGQPgakYKBFp0JaX/l2OlAqqjlODna8+8YTp3UvxOyHiA3ArufxSxc=,iv:z+ZeWFYVVIjS0eSv7UHRlRQZ+ornvKEcrx9GAFILJog=,tag:JsNlMttp2Ez29++b0o5jYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
