apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: services
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:Mg1UILpLoK7X6JPVd7V/jJBHDqACBtIzwSoq2H11gco3jCP7FhABCg==,iv:+zAqID1YvUvaGeZCKekzRdfdUHhH21o9lCKwZeyouIM=,tag:jnSqjdvBY6KftIEo0ddUWg==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:0zVC67Kss3h4,iv:O2UYAIsS5ns+1ygTCHy2f8CyQnXrbSwsAr40zGt1LYY=,tag:LuDd8Ipbcm0lRp8It+tYFA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:6lZO4YD7BKqeykj+muWbwjkXvngL6iERudH14ncoOSnT82WaQNsjzThE+t+NgQ==,iv:1FfVkGvMNFNiIJS+78L5ucNy9g0/RUNzYnaLkqaRbEs=,tag:RupFdhI/kDB8UVPeMLQ0PA==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU2x6WDY0N01VNTJMdkgv
            TDBTNWtnQ3pyZFVzanZOdWU3REhVc3FDUmdBCnF2NWw1MUc0T2xhYTkvdVltYWIy
            RU80SVNpTERHMDMvSjIvUkZacFBjc0UKLS0tIENrRGNnTk45aDVvZmRlaEFKQzlQ
            a1hUUEtwcUNGSVlVSWR4K1F6Tit4QmcKbqnk5yYq8nz5WwA/Fg2hTqppzexZQpn2
            lIlj+xNrbMjmiYUjwNhwjzICgsUs3sOIgcwCwAA2XZrc7p7dFwYR+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T15:28:13Z"
    mac: ENC[AES256_GCM,data:HaStPqNXdbORmzK2rfHeS6JAoE5zc3po4a0hVwM7JeFdv7/28vL0Yi2RngiYr12Xq1Ksd7ONlx0eifbCeRjkJ6+oIDBK9e9qiFxnxPAsWpwlhXZLbQ1KvgN50RwoAbCQ+pYNF2HYBDbCyUGAwTvITwdOOnqYDT8acWuJzcbtBOo=,iv:hNHc9Inw4Fs4VXUYqEUzL2XvOTbceOoThTbDPWLhLEM=,tag:E580pgrYfHNseK6zw+GVrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
