apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: services
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:D81X182eRoxm1jwQI1nMEkV/moUymvA8m1ukhR5yq3JWUJWKSmX9Vg==,iv:CVZZbUnqlglnM8sqhSrpMncT5SulHiLG1EpZIRqIugk=,tag:D4Zy7fJme6KCSmJbjl4ZYQ==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:ScRQe7wbxeOi,iv:Wcn+OsRtSVzKBct4E0ctpkTHkPyNwqeYg0G3C3siTpM=,tag:SnejcSg6nAD23a5J9sYpng==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:rD/QIqwTwawfbgkbUIdppZC6bCWpEi2hLaTMHUNU/Muti/rx1FyU280ZmgxsAyM=,iv:My0NASPdOE2R0IYzHi6erAny1LOUx4rYjQJV6IFI/Y0=,tag:G6rNsQUMXPgEnoPgL/VPkw==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMWpBcVpEU2l6bU1sZGNh
            VnlSUEZJeXhLTHNtOE5OeFhZUFR4NURMSFhzCmZONEhQdnFIdnBSRHE3MEVKSGl5
            L0JQQVZMUnZKcElxZzlzVTh2c1VxRWMKLS0tIEhQaGZ4WU9vQTBkbEhYVk41YW9V
            MEtORjlIaTlzOHJMMWNtU0E0ejlFZVUKK+r5zZl/+vpwC7Hoid1NPf6svzcpSLaU
            QL9oS+Xyc9HjFhqot/xLbxriIs0CM17NSGLqiPpNeoAq86xLrq22BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T15:23:51Z"
    mac: ENC[AES256_GCM,data:hdyYF9fhAx4fUMw+iJmoQ+k4VqOdTs/LD6e/LBr9Qqgd/xT6kmXf5P/bmLB+4W3u8eJ4+xMOrqSJsw9QwbZ7Q3cvC7JEwW9ScrID3sR1On76htOx5SeR71zKhEr6piMpBU9qtwP2F5LI4iiEHojq+RC2sbD+WRLAsaebk04Tdtc=,iv:DLKwdBl52VFP9yZoqnP5thrgIzkZngO1rfTqSjglUF4=,tag:6fMmm02zg0gTu2h6Wh2Jpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
