apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nexus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nexus
  values:
    controllers:
      nexus:
        containers:
          app:
            image:
              repository: sonatype/nexus3
              tag: latest
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: 8081
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteMany
        size: 20Gi
        globalMounts:
          - path: /nexus-data
