# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/prometheusrule-cluster-scaling.yaml
  - ../base/prometheusrule-ingress-health.yaml
  - ../base/prometheusrule-velero.yaml
