apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
spec:
  interval: 1h
  chart:
    spec:
      chart: velero
      version: 12.0.0
      sourceRef:
        kind: HelmRepository
        name: velero
      interval: 15m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    credentials:
      useSecret: true
      existingSecret: velero-credentials

    initContainers:
      - name: velero-plugin-for-microsoft-azure
        image: velero/velero-plugin-for-microsoft-azure:v1.14.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    configuration:
      backupStorageLocation:
        - name: default
          provider: azure
          bucket: velero
          default: true
          credential:
            name: velero-credentials
            key: cloud
          config:
            resourceGroup: Velero_Backups
            storageAccount: velero76b1f66a064d
      defaultBackupStorageLocation: default
      defaultBackupTTL: 720h0m0s
      defaultVolumesToFsBackup: true
      uploaderType: kopia
      backupSyncPeriod: 1h
      defaultRepoMaintainFrequency: 24h

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi

    backupsEnabled: true
    snapshotsEnabled: false
    deployNodeAgent: true

    schedules:
      weekly:
        schedule: "0 3 * * 0"
        template:
          ttl: 720h0m0s
          storageLocation: default
          excludedNamespaces:
            - velero
      monthly:
        schedule: "0 3 1 * *"
        template:
          ttl: 2160h0m0s
          storageLocation: default
          excludedNamespaces:
            - velero
