apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:FBCjqwIC6g6ogn32Bdl0W3ZMdNuDZGfw+KODVCpGDj+zPBxheN9datNv37dYKtujkDn8r9OWAx09vtRRmGmEps6SVHyEmXuLvtYgQ69I72kJ1Ld0VEMr3IcZBHEcpVBITZWruhkH9kGgNC7p6nblPyQUpLh4hZWi5qtkw5xxE756f5HENvUK/TnNm3/tKBWmO+WY8DcswXW+jC38eikb6TflyWxVcVulZxN9yXAmSnBeZwcBFd2z08QwpJqC+XcIP1e+v1OVHcHRNJMt0XcnjuDJd5UD/7OyaToVHpwo3rpIixU6B9ZQosIMWZAb2qy3BJeeFuAqO1tsWJsVAWwrSZD9+RqqBhAN9FxQtzdd1/1SgEmPfL3N3CALBArPh+fCufG5oaLf3B4=,iv:G0uEhGkahMgLUJPN2Ane4mlrJ+p4hECKsh1BzMl5pWk=,tag:k4RBadTQyqhP9zuFf+QYxQ==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aDZkWHRJVzBTUVQ4ZXNy
            MGRVTjFBK2tyMi9EZE41M2JNQzVJWFMrQUg4CkkzT0JsSU05ZWhoUjdMV1oxS0Vv
            U2FtT2dLcnltMlJOOWlzQnZmOEt6cGMKLS0tIDhlZUsvWlBOS3AzVXlwWFFNWnV4
            clNxL3BSUkVLYWs3YmlrRzFuUXJrQXcKfs9fS2bo0Kc0H9qkQn290fdjibXCNjSh
            O+nYCk3A/BTN/fea6+Mv7iQkRcL8TwiXRYtUqra72BPamrcRquEmlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T13:53:32Z"
    mac: ENC[AES256_GCM,data:p/Cz00hM3tu2+H5/6BGchJJhRwFuSct7yT7t6OWo6sXGYsAVVEYffx4gBKlCgcVGsBIP77PzzxkhopG7nKseeGN1FVanKsXw1gIwe18zpwkGcVqUvIfbKB8VxK7Ea6/q+i4soK/ICojm2ZtSx/9MbUKR76neTvjyEjAGCzHaRmM=,iv:49wpNKs+v/ZaK9KPNEo3ivZFxh2H1qfooh8gLXanPzo=,tag:txvbyZQpnUod3DwVZC1sFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
