apiVersion: v1
kind: Service
metadata:
  name: docker-daemon
  labels:
    app.kubernetes.io/name: docker-daemon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docker-daemon
  ports:
    - name: docker
      port: 2375
      targetPort: docker
