apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 15m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    defaultSettings:
      autoSalvage: true
      defaultReplicaCount: 3
      replicaAutoBalance: best-effort
    persistence:
      defaultClassReplicaCount: 3
      allowVolumeExpansion: true
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
    preUpgradeChecker:
      jobEnabled: false
      upgradeVersionCheck: true
