apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
  AUTHENTIK_BOOTSTRAP_PASSWORD: "${AUTHENTIK_BOOTSTRAP_PASSWORD}"
  AUTHENTIK_BOOTSTRAP_TOKEN: "${AUTHENTIK_BOOTSTRAP_TOKEN}"
  AZURE_CLIENT_ID: "${AZURE_CLIENT_ID}"
  AZURE_CLIENT_SECRET: "${AZURE_CLIENT_SECRET}"
  AZURE_TENANT_ID: "${AZURE_TENANT_ID}"
  AUTHENTIK_OIDC_CLIENT_ID: "${AUTHENTIK_OIDC_CLIENT_ID}"
  AUTHENTIK_OIDC_CLIENT_SECRET: "${AUTHENTIK_OIDC_CLIENT_SECRET}"
  SECRET_DOMAIN_0: "${SECRET_DOMAIN_0}"
