apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-issuer-secret
type: Opaque
data:
    CLOUDFLARE_CERT_MANAGER_TOKEN: ENC[AES256_GCM,data:HomW3OLha7onuYGJwcYvSbl97/XVMHPDXs6Xjbo1ZSlmt36YXMb+lg==,iv:MnZKjVTRgp91xbg0IwQT2UGy/lfMOGL+9tIPY1/+G3U=,tag:ont/o0DPDPeL3VTV50ih/g==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NUNZNUNvU3FaSk1aY2JE
            ZlA4cFpBL2c2M1RVWG0yVWVYaWZjMm1CVkN3CkJ4bDRwTWZMRzV5TnY2ZThSdUJE
            WDJkdThVcnRCSENINUlwY2tyZm9uVXcKLS0tIFVRREJNQWQ2VisyT3ZTWVRRTGhw
            MkJrZytHTUVYYWltbmZWVTFxK05pczAKgxwe7oRrlBrHu3Ew7CNYFvfCcjbCwfch
            nfqu5hnBgzGvXQpUnhjvuFPr4UCuA5b5sVihljaMjdygOY2ckvI1Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T09:42:58Z"
    mac: ENC[AES256_GCM,data:uPaMLbD1kkdPdJYRpm2la1TTGq7W6zD81KOrPlzj3935z1em/kqR4aiXgMFk1l59Pe7Jh2mhZfazDTFURQuDqOOcbTXHihuby1nfdU6O3Ha5mwSRdAh2ds58p1OBI1sTlLdyxdUAvUuNy5MopNJPLY+nvTO+TJpRLawncH75EuY=,iv:x6D3Au5J0F9kFnWuKjV12u7QhOPckhB/Br6X/EnTmKo=,tag:hFNOMdTl7Oa5K9FmNpd6KA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
