# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./custom-dns-configmap.yaml
  - ./nodeport-service.yaml
  - ./nebula-sync-secret.yaml
  - ./helmrelease.yaml
  - ./nebula-sync.yaml
