apiVersion: v1
kind: Service
metadata:
  name: pihole-headless
  namespace: network
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: pihole
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-cluster
  namespace: network
spec:
  clusterIP: 10.107.156.12
  selector:
    app.kubernetes.io/name: pihole
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns-lan
  namespace: network
  annotations:
    metallb.io/loadBalancerIPs: 10.0.69.99
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: pihole
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-admin
  namespace: network
  annotations:
    metallb.io/loadBalancerIPs: 10.0.69.98
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: pihole-0
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
