apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-home-config
  namespace: network
data:
  AdGuardHome.yaml: |
    http:
      address: 0.0.0.0:3000
      session_ttl: 720h
    users:
      - name: admin
        password: "$2a$10$Xz5E1CLc9sRiSx63VR9M2ua9cqz1OJrJIVj6wLlE5YVG5Qo2L2pwK"
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      upstream_dns:
        - https://1.1.1.1/dns-query
        - https://9.9.9.9/dns-query
        - '[/lan/]10.0.69.1'
      bootstrap_dns:
        - 1.1.1.1
        - 9.9.9.9
      fallback_dns:
        - 1.0.0.1
        - 149.112.112.112
      use_private_ptr_resolvers: true
      local_ptr_upstreams:
        - 10.0.69.1
      cache_size: 4194304
      ratelimit: 0
      rewrites: []
      blocked_hosts:
        - version.bind
        - id.server
        - hostname.bind
    filtering:
      protection_enabled: true
      filtering_enabled: true
      blocking_mode: default
      safebrowsing_enabled: false
      parental_enabled: false
      safe_search:
        enabled: false
      rewrites: []
    querylog:
      enabled: true
      interval: 2160h
    stats:
      enabled: true
      interval: 24h
    tls:
      enabled: false
    dhcp:
      enabled: false
    log:
      file: ""
      max_backups: 3
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
      verbose: false
    schema_version: 28
