apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: coder
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    coder:
      env:
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_DOMAIN_0}"
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-app
              key: uri
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
        - name: CODER_OIDC_ISSUER_URL
          value: "https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0"
        - name: CODER_OIDC_CLIENT_ID
          value: "${AZURE_CLIENT_ID}"
        - name: CODER_OIDC_CLIENT_SECRET
          value: "${AZURE_CLIENT_SECRET}"
        - name: CODER_OIDC_EMAIL_FIELD
          value: upn
        - name: CODER_OIDC_GROUP_FIELD
          value: groups
        - name: CODER_OIDC_SCOPES
          value: openid,profile,email,offline_access
        - name: CODER_OIDC_SIGN_IN_TEXT
          value: Sign in with Microsoft Entra ID
        - name: CODER_PROMETHEUS_ENABLE
          value: "true"
        - name: CODER_PROMETHEUS_ADDRESS
          value: 0.0.0.0:2112
      service:
        type: ClusterIP
      ingress:
        enable: false
      serviceAccount:
        workspacePerms: true
      securityContext:
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
