apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aiostreams
  namespace: flux-system
spec:
  targetNamespace: services
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: true
  path: ./kubernetes/apps/services/aiostreams/base
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: longhorn
  wait: false
