apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flux-operator
  namespace: network
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux.${SECRET_DOMAIN_0}`)
      kind: Rule
      services:
        - name: flux-operator
          namespace: flux-system
          port: 9080
  tls: {}
