# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./middlewares.yaml
  - ./authentik.yaml
  - ./flux-operator.yaml
  - ./longhorn.yaml
  - ./homeassistant.yaml
  - ./aiostreams.yaml
  - ./traefik.yaml