apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: pihole-sticky
  namespace: network
spec:
  weighted:
    services:
      - name: pihole-web
        namespace: network
        port: 80
        weight: 1
    sticky:
      cookie:
        name: pihole_sticky
        secure: true
        httpOnly: true
        sameSite: strict
