apiVersion: v1
kind: Secret
metadata:
  name: telegram-notification
  namespace: monitoring
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:bg7t7JZLeRslopuJSVvPL8QUFN9nTN29GLHiYdheJy4upth3KKwQP+0xOOvXbw==,iv:DkoUGdwdUk6K1811FD8hQqnTiiUyHxOHE/Nzsp9NL18=,tag:/FHbdc8QkpfvuZ2QGylzIw==,type:str]
sops:
  age:
    - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaGRBR3hPakRBSURGQzd4
        YTRaNWV3WDFnL0dXdmloZHRseGxZbSt0cmg0CnJaVW10b3JaYTIvWHprd3lZYVpu
        TUdhUk1uaFVsRkdqUUJwQXlPT0ZFeTAKLS0tIGxiN3BIeWhHZEQzbXIzSzlTckd4
        ZUp0dzhoV0p3QkZhcGRXa0ZkTHhzS0kKfZNlbPBwtXdvDa8rtWEEJB+nDe8xsdqy
        KHR/RcrvOlLZ3QYlv6aeUiBKhCmYfsLBFphtqs25YUBaMm5Ss2FGcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-30T14:50:26Z"
  mac: ENC[AES256_GCM,data:4gbklgo4clzEFDpyCQE+52L2PERCcfJuEZpb6+G6x3rquQt0wNqdHL+BlKjVKmf8gqDcY2fntwQ3sBMAxXzmRKt5gFf521hp/w2K4yRfIjm2vj77TEsR4zvUOwIMZMEtLB1lZlkMGBYBkNQA8mgRG1cucBA7Fvlf5H12P0Yj40w=,iv:QUHrDMIISPjsXS1rrSISmva89tXIzZADZfGuF3it9z0=,tag:9X7A18DUVid+N2fjpQ1k0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
