apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/my-cluster/flux-system"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
