apiVersion: v1
kind: Secret
metadata:
    name: flux-system
    namespace: flux-system
type: Opaque
data:
    identity: ENC[AES256_GCM,data:0i4qrL/0GsQ9t+bM3tBFtV28r7dmykg5k/TSMukqO/KyHIKhFEG/abgy53/8bceJahx9GHO+zE2DF/6UQmcHYTXYRzAjqBtayipEevmn+QNDi3thkEFHGjw9crRkgnbgtcmSUOZ3jkQXyh/vlKeXjQanXZjFVOeeZWSa+aIm0xfEfxIh7JcTFO3cHYjSzhSSAtfvWze2ZdDLCRzgwD0BDUeV0V8Rvh6qos/zjbJ/gZ+lylRNO8dlC2IwRKJ53MJ5UYM9NBuw6eRKEO4AidT+cxpO65qQn8TD6eKYCEC4zHC7dya42GKytGLkC6RPr+ZaOo1FJ0N62RDje41ihoqFNKHzntdCL3+Kr+ID0L3XXUiITvZgByAm2H7u2MaQqKwYW0PAWjbLHZ5abAcNZpT7ff6WAfSACGHXDMvoPihtupKvoH2d3BMLSVmfg0KpMFylAwRT/9Dsjawrtj74bD/hPvnGGHWabimRLEuqbtmVg23iJjduAFjLe73rhAGn3RNuXaB/FGTU7bNPxvCynDuF6YGteMuZ1+si,iv:Ai4d4BxzHrGcjkSxFdcM5KXf9nTjFVAJwwWXMOKKLd0=,tag:1s+Y30/tE7p53tXFu7faLw==,type:str]
    identity.pub: ENC[AES256_GCM,data:PxVM2m4pbrtQiElW9QEm/Lv4lvCjvc6gsL5iCTsRH72SK2wYRkGv4haFaF+veO/DmSCs7bzxlZyh3NZdVvxWpvBOdLaJqJODdzVodc+UZC8KB48PeejZu5bpJrXJXZWQs4+XFH3EJ5rMoqFFjL4V2TgKkBY29IyX9R7glnVNJmmPmEBIeSMd7w7thFwnoqFPaxqJTcZZKERKvZl3j2LKW6kpTebDRghjJw7l4pTB/UWubBLDMiNMKhNfLTZ+JwP03SstCyhEc2KvxjkK6mq2aXwHa6QEMYxHfqp9RUn2tOdzTXSlnZd21SqRvWihEkjDVNkv5rp2gY3Arm8EeLvQ5b/G/N+TmBWYhNnPf88FL3M5UiSp,iv:RGo/9I4bjVvXIzRTasDhsdn1SeI2C1eOJR0NRLZkMU4=,tag:hBS0AGpC8/VocJtnL9J+Jg==,type:str]
    known_hosts: ENC[AES256_GCM,data:2/BeC4ID4nwVZ08W5VsB0Vugv8wwsFrpaX2H2XzsoJfiGJgHRTu7qhMtCdN+QCv6MOdhTp/MQsn3Yn8N6z7mjF1alke0w79yGe0bhGP3Hki+LwYRB0slZCp8hzMET810bqfvS4MHPZsm6xE0HVyZ6UYT4Tt7xgzLQ2l9hJa8AEiXkcIACYxS2IYREVVSywn2Whxzgxyh4rhgMsuaA397lbdzQhCv0wEcdxjW/Z/VLQA5JnMnLDGiFr8YDphzq58OekXO5JE8YEnb7NJdUq4eSO9caJ0Dca98aspsMQhldCVGm3Qe,iv:aiZFxownnfZzbktvl3BkLXx9hZWR1yjOs0FzprNwDM4=,tag:kskDrvBKhrq6wQ27IHf15Q==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQnVRQW9sUGpsbjdQQTNG
            MjBrNE1nUjFjaHE5VWdzZkp2eWNOaWduZ21RCmhsRG5QK2N2SjJvY0huL3hDb0Nv
            QWZ0Ykd1bUUyL2gxcUhLTU9GUzFwbUEKLS0tIHc0TDgwUkowY0V1SWZyRmY5MmNZ
            cUczcEVTTHcxN0w4MGxtSjFDdHdXV1kKbGhIEup9CubWvshjLPFbOUJQ2N7v/oFO
            doJbGncxlFLxFn//vqpx5956TC7+0zdULtCP2Y/CoKJ2NFGG5ldEkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T09:03:57Z"
    mac: ENC[AES256_GCM,data:CIrkbH8L7MTaCP9wkZbzhdjW5/wH0BKKuFgXby7qiYnR4Mu8iDZi/xKDI6hurWDL+H4agoAnS3hqKGq2fArpraONeQFEI2SlpPzmI1gE7dswG6sDeAqF+M7ddn8edFPnywHSy2y9GKbVdCJDd2NAW+2eimBrJDKGRkeXSaa5a+w=,iv:yt1Odeh7N58m+R2zlvpt6oI6hTwOc7Pgf5KF3bucI60=,tag:+jG1w29+WJmJivxJNZkwIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
