# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secret
    namespace: services
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:KkM6K9V9irEapuMQ6HQkKfjPXUlGkqlbjOXskACIuQTTanCMJCzFLa4EW793AHlrBiI2j7ZfM4IziB/6fzLBpA==,iv:8cI9+zWs2jPMIFro0//+V36WVhLI66T3F+EPB26/Qhk=,tag:M+qN9NtepfSeKtTLatKuYQ==,type:str]
    ADDON_PASSWORD: ENC[AES256_GCM,data:MyyMuUas8wRHwzE/UhEca+MGGqU/hd/8,iv:Wps2i1iWBd4IUdV8Imkk6qyaS9LhEpPQmdqhQRsJVe4=,tag:K+v0fWRYbP0SUbrzseci5Q==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dExWaTFuMWYxL0J1UEZ2
            dll0b2xJWWtmR3lySm56WjNQZ0dxTEo1bUJjCjlHQW50bE55YkRKZTZQa3hISG8v
            WWd6cUNPVjR6Z3lKK2JtcXk2aUg0aFkKLS0tIE5EclB2NzVvQW5ENW40M0dHUndN
            SndtTjg3QmdrcS93VS96NStFU293cnMKLjm29HHxkkX6LhM4zGXzEYtV6b7lTWLL
            qgzEQ+p4qDINOlEU81uF8vQ99Z1FSOWJpP5FcuEZvGVX34rtpf9nXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T14:49:50Z"
    mac: ENC[AES256_GCM,data:bnV5D63c4hMe5+ulmqWADQ4URxEmfZCXJUvHJRBhvwqeObVk54xgM7sQsl2Djo+RFmnRBX3K/18jRaObki0osgQhKCfswvoTtdz9ngzXNT2H68qxUAdlYqawtyf+x8VrF5W9MobBOQB0UbEteY82zkbHnOsZlEog4E/LpVCMfTc=,iv:uXtXXaklIzJMVwnMeJmo/4x2hLqlTMSQAH45lGY5vbE=,tag:7W3Ze14Vojx76sZ19rarmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
