apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aiostreams
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: aiostreams
  values:
    controllers:
      aiostreams:
        containers:
          app:
            image:
              repository: ghcr.io/viren070/aiostreams
              tag: latest
            envFrom:
              - secretRef:
                  name: aiostreams-secret
            env:
              TZ: "${TZ}"
              ADDON_NAME: "AIOStreams"
              ADDON_ID: "aiostreams.${SECRET_DOMAIN_0}"
              PORT: "3000"
              BASE_URL: "aiostreams.${SECRET_DOMAIN_0}"
              SECRET_KEY: "${AIOSTREAM_SECRET_KEY}"
              ADDON_PASSWORD: "${AIOSTREAM_ADDON_PASSWORD}"
              DATABASE_URI: "sqlite://./data/db.sqlite"
              BUILTIN_STREMTHRU_URL: "https://stremthru.13377001.xyz"
              BUILTIN_SCRAPE_WITH_ALL_TITLES: "false"
              BUILTIN_DEBRID_INSTANT_AVAILABILITY_CACHE_TTL: "1800"
              BUILTIN_DEBRID_PLAYBACK_LINK_CACHE_TTL: "3600"
              BUILTIN_GET_TORRENT_TIMEOUT: "5000"
              BUILTIN_GET_TORRENT_CONCURRENCY: "100"
              BUILTIN_PROWLARR_SEARCH_CACHE_TTL: "604800"
              BUILTIN_PROWLARR_INDEXERS_CACHE_TTL: "1209600"
              BUILTIN_GDRIVE_PAGE_SIZE_LIMIT: "1000"
              BUILTIN_TORBOX_SEARCH_SEARCH_API_TIMEOUT: "30000"
              BUILTIN_TORBOX_SEARCH_CACHE_PER_USER_SEARCH_ENGINE: "false"
              BUILTIN_NAB_SEARCH_TIMEOUT: "30000"
              BUILTIN_NAB_SEARCH_CACHE_TTL: "604800"
              BUILTIN_NAB_CAPABILITIES_CACHE_TTL: "1209600"
              BUILTIN_ZILEAN_URL: "https://zilean.elfhosted.com"
              BUILTIN_ANIMETOSHO_URL: "https://feed.animetosho.org"
              ANIME_DB_LEVEL_OF_DETAIL: "required"
              ANIME_DB_FRIBB_MAPPINGS_REFRESH_INTERVAL: "86400000"
              ANIME_DB_MANAMI_DB_REFRESH_INTERVAL: "604800000"
              ANIME_DB_KITSU_IMDB_MAPPING_REFRESH_INTERVAL: "86400000"
              ANIME_DB_EXTENDED_ANITRAKT_MOVIES_REFRESH_INTERVAL: "86400000"
              ANIME_DB_EXTENDED_ANITRAKT_TV_REFRESH_INTERVAL: "86400000"
              TMDB_ACCESS_TOKEN: ""
              TMDB_API_KEY: ""
              TRAKT_CLIENT_ID: ""
              DEFAULT_REALDEBRID_API_KEY: ""
              FORCED_REALDEBRID_API_KEY: ""
              DEFAULT_ALLDEBRID_API_KEY: ""
              FORCED_ALLDEBRID_API_KEY: ""
              DEFAULT_PREMIUMIZE_API_KEY: ""
              FORCED_PREMIUMIZE_API_KEY: ""
              DEFAULT_DEBRIDLINK_API_KEY: ""
              FORCED_DEBRIDLINK_API_KEY: ""
              DEFAULT_TORBOX_API_KEY: ""
              FORCED_TORBOX_API_KEY: ""
              DEFAULT_OFFCLOUD_API_KEY: ""
              FORCED_OFFCLOUD_API_KEY: ""
              DEFAULT_OFFCLOUD_EMAIL: ""
              FORCED_OFFCLOUD_EMAIL: ""
              DEFAULT_OFFCLOUD_PASSWORD: ""
              FORCED_OFFCLOUD_PASSWORD: ""
              DEFAULT_PUTIO_CLIENT_ID: ""
              FORCED_PUTIO_CLIENT_ID: ""
              DEFAULT_PUTIO_CLIENT_SECRET: ""
              FORCED_PUTIO_CLIENT_SECRET: ""
              DEFAULT_EASYNEWS_USERNAME: ""
              FORCED_EASYNEWS_USERNAME: ""
              DEFAULT_EASYNEWS_PASSWORD: ""
              FORCED_EASYNEWS_PASSWORD: ""
              DEFAULT_EASYDEBRID_API_KEY: ""
              FORCED_EASYDEBRID_API_KEY: ""
              DEFAULT_DEBRIDER_API_KEY: ""
              FORCED_DEBRIDER_API_KEY: ""
              DEFAULT_PIKPAK_EMAIL: ""
              FORCED_PIKPAK_EMAIL: ""
              DEFAULT_PIKPAK_PASSWORD: ""
              FORCED_PIKPAK_PASSWORD: ""
              DEFAULT_SEEDR_ENCODED_TOKEN: ""
              FORCED_SEEDR_ENCODED_TOKEN: ""
              CUSTOM_HTML: ""
              ALTERNATE_DESIGN: "false"
              REGEX_FILTER_ACCESS: "all"
              DEFAULT_MAX_CACHE_SIZE: "100000"
              PROXY_IP_CACHE_TTL: "900"
              MANIFEST_CACHE_TTL: "21600"
              SUBTITLE_CACHE_TTL: "300"
              STREAM_CACHE_TTL: "-1"
              CATALOG_CACHE_TTL: "300"
              META_CACHE_TTL: "300"
              ADDON_CATALOG_CACHE_TTL: "300"
              RPDB_API_KEY_VALIDITY_CACHE_TTL: "604800"
              DISABLE_SELF_SCRAPING: "true"
              LOG_LEVEL: "http"
              LOG_FORMAT: "text"
              LOG_SENSITIVE_INFO: "true"
              LOG_TIMEZONE: "Etc/UTC"
              DEFAULT_PROXY_ID: "mediaflow"
              FORCE_PROXY_DISABLE_PROXIED_ADDONS: "false"
              ENCRYPT_MEDIAFLOW_URLS: "true"
              ENCRYPT_STREMTHRU_URLS: "true"
              DEFAULT_TIMEOUT: "7000"
              MAX_ADDONS: "15"
              MAX_GROUPS: "20"
              MAX_KEYWORD_FILTERS: "30"
              MAX_STREAM_EXPRESSION_FILTERS: "30"
              MAX_TIMEOUT: "50000"
              MIN_TIMEOUT: "1000"
              PRECACHE_NEXT_EPISODE_MIN_INTERVAL: "86400"
              DISABLE_RATE_LIMITS: "false"
              STATIC_RATE_LIMIT_WINDOW: "5"
              STATIC_RATE_LIMIT_MAX_REQUESTS: "75"
              USER_API_RATE_LIMIT_WINDOW: "5"
              USER_API_RATE_LIMIT_MAX_REQUESTS: "5"
              STREAM_API_RATE_LIMIT_WINDOW: "5"
              STREAM_API_RATE_LIMIT_MAX_REQUESTS: "10"
              FORMAT_API_RATE_LIMIT_WINDOW: "5"
              FORMAT_API_RATE_LIMIT_MAX_REQUESTS: "30"
              CATALOG_API_RATE_LIMIT_WINDOW: "5"
              CATALOG_API_RATE_LIMIT_MAX_REQUESTS: "5"
              ANIME_API_RATE_LIMIT_WINDOW: "60"
              ANIME_API_RATE_LIMIT_MAX_REQUESTS: "120"
              STREMIO_STREAM_RATE_LIMIT_WINDOW: "15"
              STREMIO_STREAM_RATE_LIMIT_MAX_REQUESTS: "10"
              STREMIO_CATALOG_RATE_LIMIT_WINDOW: "5"
              STREMIO_CATALOG_RATE_LIMIT_MAX_REQUESTS: "30"
              STREMIO_MANIFEST_RATE_LIMIT_WINDOW: "5"
              STREMIO_MANIFEST_RATE_LIMIT_MAX_REQUESTS: "5"
              STREMIO_SUBTITLE_RATE_LIMIT_WINDOW: "5"
              STREMIO_SUBTITLE_RATE_LIMIT_MAX_REQUESTS: "10"
              STREMIO_META_RATE_LIMIT_WINDOW: "5"
              STREMIO_META_RATE_LIMIT_MAX_REQUESTS: "15"
              PRUNE_INTERVAL: "86400"
              PRUNE_MAX_DAYS: "-1"
              SEL_SYNC_ACCESS: "all"
              WHITELISTED_SYNC_REFRESH_INTERVAL: "86400"
              MAX_STREAM_EXPRESSIONS: "200"
              MAX_STREAM_EXPRESSIONS_TOTAL_CHARACTERS: "50000"
              MAX_SEL_LENGTH: "3000"
            securityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: true
              capabilities:
                drop: ["ALL"]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        ports:
          http:
            port: 3000
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteMany
        size: 10Gi
        globalMounts:
          - path: /app/data
