apiVersion: v1
kind: Secret
metadata:
    name: stremthru-secret
    namespace: services
stringData:
    STREMTHRU_AUTH: ENC[AES256_GCM,data:DrxC/ltC/xNP/MVmvW9UU/uZQ26BjLP2F+jOMB9kG2OU+lsL2RoWUHhtgA==,iv:/Dl9JaS+RUSYtyldwFVsTc22lJK3FQ6RZQRNC5BtMf8=,tag:BbhgDrFwG3SS6wLPvlMN3A==,type:str]
    STREMTHRU_AUTH_ADMIN: ENC[AES256_GCM,data:6BV8CWR6v5Rhig==,iv:zt+a2la53p+GM6ddv1UTM9NldZ1dwZ+5aVrgntT0QYk=,tag:IQAlzDwT7MxvfG2OSqDnoQ==,type:str]
    STREMTHRU_VAULT_SECRET: ENC[AES256_GCM,data:p1Ou7nSfEpNKJfBLHpZNu824Ye/hGn5qzhHliaLaQOH8QWhKK4XI1kp7RaFofrF/0CfZzBZzR4HAzUYv9wb7jg==,iv:90mZbv0b60410VIFux1K0yyYy/FNsGoNjO9jnDbQrw0=,tag:G55uAeI3JPlybK2GXsylLw==,type:str]
    DEFAULT_PROXY_CREDENTIALS: ENC[AES256_GCM,data:ineCLlb4jT1pPWqpzN7HOaSTCVUfowroJH7NFclrUBE3B0WNBGZx9HjLmw==,iv:ffNhRJW8d+HiBQnE+twQTTrh9RfGEqUQJQYhVmCZ1Eo=,tag:6Ts0kqCkHL662QgtyLIojg==,type:str]
    FORCE_PROXY_CREDENTIALS: ENC[AES256_GCM,data:Kw4gsQXMr5aMEwu6QFQUvqwXV1wWnQBRuo5v58KXbyGeLqctuNZjkpwd7A==,iv:CVwjSaoA67IMuZ1NSWazWoc0DYUoxpGFWhRIZj9875I=,tag:ECwz63rj1oOPeldHprplEw==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQlRyMTdlNXNzazVId3N3
            UmQ5SkxXakdEZ1FZelVrcTgzeEY1eElEa2c0CnB3R3BRQkFkb1Qwd1lMWXZyb1Z2
            REdkMFlMUWp0bm9hR0hzb0tLT0plYlEKLS0tIGlYaEx6SDErNmdWS2NVSUpkdzMr
            dnhwd2J1UjNvaENSRzc1SGF3Y2Y1clkKR+BCWqP8v3Dfwf/a5U3MD+SXERxcsYVC
            +qs7SmHHFDArKuVqHcFS+KbYLQVpPM139LcCJtSJId74Mya/4S1WEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T19:58:32Z"
    mac: ENC[AES256_GCM,data:GJV3HudK0JMvizXEQpscsZ6GQ8ABwVhoLF2agBhdy2c98VFYzjr/bGnLxtMzvgTGhFv7SaAtjbGjuKbE8XK1BTFZi/I7zJTT53jRkX0DIRDncsf8hq6hahu763GI5D5A9vLJ1aHgayjj3SBym6toAu7RCbB1ZvG/llcfpZnJCO0=,iv:EYaNYmkzj5iHWayMXz+r+FgIpO+FbzqcWytUbsXHdAc=,tag:OjV8M0ENpidiz5CqXTS4XA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
