# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: esphome-dist-client-secret
    namespace: services
stringData:
    SERVER_TOKEN: ENC[AES256_GCM,data:kgiSLeqljffYH35sQ6yuD22c0XBvP/KVMbmIaZWd1KQ=,iv:b6WZWkpYecKuC83P41P/HjUm/r4/QJuGXQRu+lpCzCE=,tag:HtDer3UPqve33Cvel/JqXg==,type:str]
sops:
    age:
        - recipient: age10qpu76yk6rvyaunmsadkej3l0pwuk4mn4uhxnem4cyl9zjrucgmsndh72v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeGtMWkJTNDlGdldHQ1Zi
            QjRiTWdIdWc1ZnZQcVZZUnFGRFlYbWhjVTI4Clk2dndjVEhHQmM0V2kxbFJxL1FV
            cmNxRUljdjVpb09FWVRjN3dtMFhlYTAKLS0tIG5mV1V2WlRwR3FaL1RsQ0pZWWl4
            Y2V2MERWc2xIKzFpSXA5djFOSGFMSGMKxjDKiF9hTwPsucJM4xAvXdO6vhGvteuQ
            LIVS9pn/FX7tfjPSsm3CdZqHafwX6105GzrEeSj93xMZ0xp9Ois4AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T03:01:12Z"
    mac: ENC[AES256_GCM,data:nyyn7lD4haHIc7vlJOmdNSb4CxBG2+z95FYzWmfTY7ZwzrL4v82uVjr4M7klzcKVmY+c+Q8gTDnSCfbTUwZg6uAuKjgFB3zykuKRSMjIoOnnXI4IMCCsKbLqhZ8fSA2Pr2Erud87/xnPSfgXtEpAp5zjsk0ib/HKfhns1jfI99g=,iv:zTrTI8PH+mmWmRhXFPEd2fKeXSeltaEwChKZF6GruwI=,tag:QUBYvFqEs0nUO7kDqaOJPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
