apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome-dist-client
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: esphome-dist-client
  values:
    controllers:
      esphome-dist-client:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/weirded/esphome-dist-client
              tag: 1.6.1
            env:
              SERVER_URL: "${ESPHOME_DIST_CLIENT_SERVER_URL}"
              SERVER_TOKEN: "${ESPHOME_DIST_CLIENT_SERVER_TOKEN}"
              MAX_PARALLEL_JOBS: "2"
              ESPHOME_SEED_VERSION: "${ESPHOME_DIST_CLIENT_SEED_VERSION}"
              HOSTNAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources: {}
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
    persistence:
      esphome-versions:
        type: hostPath
        hostPath: /var/lib/esphome-versions
        globalMounts:
          - path: /esphome-versions
