apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome-dist-client
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: esphome-dist-client
  values:
    controllers:
      esphome-dist-client:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/weirded/esphome-dist-client
              tag: 1.0.0
            env:
              SERVER_URL: "http://10.0.100.11:8765"
              SERVER_TOKEN: "${ESPHOME_DIST_CLIENT_SERVER_TOKEN}"
              MAX_PARALLEL_JOBS: "2"
              ESPHOME_SEED_VERSION: "2026.3.1"
              HOSTNAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
    persistence:
      esphome-versions:
        type: hostPath
        hostPath: /var/lib/esphome-versions
        globalMounts:
          - path: /esphome-versions
